language: rust
cache: cargo
env: # required for allow_failures
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt -- --check
        - cargo clippy -- -D clippy

addons: # required for kcov
  apt:
    packages:
      - libpcap-dev

script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose

branches:
  only:
    - staging # bors r+
    - trying  # bors try
    - master
